pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh 'echo "Building stages..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
            }
        }

        stage('Docker Build') {
            steps {
                dir('jenkins-Demo') {
                    sh 'docker build -t jenkins-demo .'
                }
            }
        }

        stage('Docker Test') {
            steps {
                dir('jenkins-Demo') {
                    sh 'docker run --rm jenkins-demo'
                }
            }
        }

    }
}