pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Build stage"
                dir('jenkins-Demo') {
                    sh 'chmod +x app.sh'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-Demo') {
                    sh './test.sh'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('jenkins-Demo') {
                    sh 'docker build -t jenkins-demo .'
                }
            }
        }

        stage('Docker Test') {
            steps {
                sh 'docker run --rm jenkins-demo'
            }
        }

    }
}